#NAME #IMPORT commands, minor changes in scripts and user manual

diff --git a/dkparse/scripts/dk2mmt b/dkparse/scripts/dk2mmt
--- a/dkparse/scripts/dk2mmt
+++ b/dkparse/scripts/dk2mmt
@@ -4,4 +4,4 @@ then
 	echo "Usage: dk2mmt input.dk output.mmt"
 	exit 1
 fi
-dkc --mmt -o $2 $1
+dkc --mmt -o $2 $1 && echo 1>&2 'SUCCESS' || ( echo 1>&2 'FAILURE' ; exit 1 )
diff --git a/dkparse/scripts/dkcompile b/dkparse/scripts/dkcompile
--- a/dkparse/scripts/dkcompile
+++ b/dkparse/scripts/dkcompile
@@ -1,2 +1,8 @@
 #!/bin/bash
-dkc -q -c $*
+if [ $# -ne 2 ]
+then
+	echo "Usage: dkcompile input.dk output.lua"
+	exit 1
+fi
+ 
+dkc -q -c -o $2 $1 && echo 1>&2 'SUCCESS' || ( echo 1>&2 'FAILURE' ; exit 1 )
